apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211159-post-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend/post
  template:
    metadata:
      labels:
        app: backend/post
    spec:
      containers:
      - name: backend/post
        image: harisathar04/post:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: i211159-post-service
spec:
  selector:
    app: backend/post
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer