apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211159-classroom-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend/classroom
  template:
    metadata:
      labels:
        app: backend/classroom
    spec:
      containers:
      - name: backend/classroom
        image: harisathar04/classroom:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: i211159-classroom-service
spec:
  selector:
    app: backend/classroom
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer